# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'windows-latest'

env:
  PACKAGE_PATH: 'src/WebFrontEnd/ClientApp'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli --prefix ${{env.PACKAGE_PATH }}
    npm install --prefix ${{env.PACKAGE_PATH}}
    ng build --prod --prefix ${{env.PACKAGE_PATH}}
  displayName: 'npm install and build'
