# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli --prefix 'src/WebFrontEnd/ClientApp'
    npm install --prefix 'src/WebFrontEnd/ClientApp'
    ng build --prod --prefix 'src/WebFrontEnd/ClientApp'
  displayName: 'npm install and build'
